use_frameworks!
platform :ios, '11.0'

target 'MtsInvestGrpcService_Example' do

  pod 'gRPC-Swift'
  pod 'MtsInvestGrpcService', :path => '../'

  target 'MtsInvestGrpcService_Tests' do
    inherit! :search_paths

  end
end
